### ISSUE TITLE
Zillow links throw error on loading image with showMultimedia set to true.

### ISSUE THREAD

**Issue by tdrast** [sur950/any_link_preview#15]
Tested Zillow links with the example application.  The image load fails periodically with a null image.  "type 'Null' is not a subtype of type 'List<int>' in type cast on NetworkImage._loadAsync."  It appears to be a timing issue with the image availability.

Example URL: "https://www.zillow.com/homedetails/26828-Willow-Creek-Ln-UNIT-25-Santa-Clarita-CA-91355/55822242_zpid/"

**Comment by sur950** [comment]
Hey, Thanks for using the plugin.

Seems this website isn't giving proper image URL's. You can always verify things by opening the link in browser, search for meta tags & see if the content is valid or not.

I am closing the issue since the there's no valid image URL that is being provided by the website. Feel free re-open the issue if you see the image url's are valid.

Cheers,
Suresh
