### ISSUE TITLE
Can't get domain name of websites 

### ISSUE THREAD

**Issue by Helocominc** [sur950/any_link_preview#39]
Add the option to get domain name of the website url in `metadata`. Instead of displaying the full url just show the domain. 
![Issue](https://user-images.githubusercontent.com/90664424/199545915-68ed73b6-f77d-4ba9-a0cd-f0daf0778e19.jpg)

This is the expected domain sample 
![expected](https://user-images.githubusercontent.com/90664424/199545949-e19aa32d-d90b-494d-b5b4-86b4f339b7a8.jpg)

**Comment by LeGoffMael** [comment]
You can do that on your side as well

```dart
String getUrlHost(String url) {
  Uri uri = Uri.parse(url);
  return uri.host.replaceFirst(RegExp(r"^www."), '');
}
```

**Comment by Helocominc** [comment]
Okay thanks. I will try that.

**Comment by sur950** [comment]
Hi @Helocominc 

We are not rendering the title, or body manually. Whatever the meta-data is giving us, we are rendering the same. 
I guess for youtube videos, it is giving full length instead of just the domain name or some description.

You can always use your method to fetch meta-data and render your own UI by using the above-mentioned helper function.
Thanks for helping the community @LeGoffMael 

Regards,
Suresh
